<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SporeholmLauncher.Cli</RootNamespace>
    <AssemblyName>sporeholm-launcher-cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SporeholmLauncher.Core\SporeholmLauncher.Core.csproj" />
  </ItemGroup>

</Project>
